# Generated by Django 2.2.1 on 2019-05-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0002_auto_20190525_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='event_cover',
            field=models.TextField(default='https://fund-rest-framework.s3.amazonaws.com/af-logo-square-transparent-130.png'),
            preserve_default=False,
        ),
    ]
